#!/bin/sh

set -e

lb config noauto \
	--updates "false" \
	--security "false" \
	--architecture "amd64" \
	--cache-packages "false" \
	--distribution "bookworm" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--image-name "rename-it" \
	--iso-application "KoruX" \
	--iso-publisher "KoruX GNU/Linux" \
	--iso-volume "KoruX 0.01 Xfce amd64" \
	--bootloaders "grub-pc grub-efi" \
	--bootappend-live "boot=live components quiet username=user hostname=live-korux" \
	"${@}"
