#!/bin/sh

set -e

lb config noauto \
	--updates "false" \
	--security "false" \
	--architecture "amd64" \
	--cache-packages "false" \
	--debian-installer "live" \
	--distribution "bookworm" \
	--debian-installer-distribution "bookworm" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--image-name "rename-it" \
	--iso-application "Korux" \
	--iso-publisher "Korux GNU/Linux" \
	--iso-volume "k-live 0.01 xf amd64" \
	"${@}"

cp /usr/share/doc/live-build/examples/hooks/reproducible/* config/hooks/normal
rm -f config/hooks/normal/README
